Determine the **accuracy** of detections

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm_notebook as tqdm
from Functions import utilities
import os


**User-Defined** inputs

In [4]:
predictionsdirectory='/home/manan/Desktop/01_Projects/25_Tomas_GradientLOG/03_Output/source/27102018/01_Blobs/'
groundtruthdirectory='/home/manan/Desktop/01_Projects/25_Tomas_GradientLOG/01_Data/BM_dataset_MICCAI2015/annotations/'
saveresultsdirectory='/home/manan/Desktop/01_Projects/25_Tomas_GradientLOG/03_Output/'

**Pre-processing**

In [5]:
TP=[]
FP=[]
FN=[]
recall=[]
precision=[]
jaccardindex=[]
F1score=[]
filename=[]
    

Evaluate metrics in **standard** fashion : radius threshold of 8 pixels

In [6]:
for predictionsfilename in tqdm(os.listdir(predictionsdirectory)):
    blobs, headerdictionary=utilities.getDataAndHeader(predictionsdirectory, predictionsfilename)
    groundtruthfilename=predictionsfilename[:-4]+'_dots.png'
    groundtruthaddress=groundtruthdirectory+groundtruthfilename
    groundtruthimage=plt.imread(groundtruthaddress)
    groundtruthyx=np.array(np.nonzero(groundtruthimage)).T
    predictionsyx=blobs[:, 1:3]
    TPi, FPi, FNi, recalli, precisioni, jaccardindexi, F1scorei=utilities.evaluateMetricsStandard(predictionsyx, groundtruthyx, radius=8)
    TP.append(TPi)
    FP.append(FPi)
    FN.append(FNi)
    recall.append(recalli)
    precision.append(precisioni)
    jaccardindex.append(jaccardindexi)
    F1score.append(F1scorei)
    filename.append(predictionsfilename)


IndexError: too many indices for array

In [54]:
resultsstandard= list(zip(filename, TP, FP, FN, recall, precision, jaccardindex, F1score))
import pandas as pd
df=pd.DataFrame(resultsstandard, columns=['filename', 'TP', 'FP', 'FN', 'recall', 'precision', 'jaccardindex', 'F1score'] )
df.to_csv(saveresultsdirectory+'resultsstandard.csv', sep='\t')
#np.savetxt(saveresultsdirectory+'resultsstandard.csv', resultsstandard, delimiter='\t' )

Evaluate metrics in **scale-space** fashion

In [59]:
TP=[]
FP=[]
FN=[]
recall=[]
precision=[]
jaccardindex=[]
F1score=[]
filename=[]

In [60]:
for predictionsfilename in tqdm(os.listdir(predictionsdirectory)):
    blobs, headerdictionary=utilities.getDataAndHeader(predictionsdirectory, predictionsfilename)
    groundtruthfilename=predictionsfilename[:-4]+'_dots.png'
    groundtruthaddress=groundtruthdirectory+groundtruthfilename
    groundtruthimage=plt.imread(groundtruthaddress)
    groundtruthyx=np.array(np.nonzero(groundtruthimage)).T
    predictionsyx=blobs[:, 1:3]
    
    if (headerdictionary['datatype']=='2D'):
        radiusprediction=np.sqrt(2)*blobs[:,0]
        radiusmatrix=np.repeat(radiusmatrix, np.shape(groundtruthyx)[0], axis=1)
    
    else:
        radiusprediction=np.sqrt(3)*blobs[:,0]
        radiusmatrix=np.repeat(radiusmatrix, np.shape(groundtruthyx)[0], axis=1)
        
    TPi, FPi, FNi, recalli, precisioni, jaccardindexi, F1scorei=utilities.evaluateMetricsScaleSpace(predictionsyx, groundtruthyx, radius=radiusprediction)
    TP.append(TPi)
    FP.append(FPi)
    FN.append(FNi)
    recall.append(recalli)
    precision.append(precisioni)
    jaccardindex.append(jaccardindexi)
    F1score.append(F1scorei)
    filename.append(predictionsfilename)


AttributeError: module 'Functions.utilities' has no attribute 'evaluateMetricsScaleSpace'

In [ ]:
resultsscalespace= list(zip(filename, TP, FP, FN, recall, precision, jaccardindex, F1score))
import pandas as pd
df=pd.DataFrame(resultsstandard, columns=['filename', 'TP', 'FP', 'FN', 'recall', 'precision', 'jaccardindex', 'F1score'] )
df.to_csv(saveresultsdirectory+'resultsscalespace.csv', sep='\t')


In [58]:
headerdictionary['datatype']=='2D'


True

In [9]:
from scipy.spatial import distance_matrix
distance_matrix([[2,3],[1,10]], [[5,4],[1,1]])

array([[3.16227766, 2.23606798],
       [7.21110255, 9.        ]])

In [14]:
a=np.random.rand(5,1)

In [15]:
np.repmat(a, 3)

AttributeError: module 'numpy' has no attribute 'repmat'

In [16]:
[a]*3

[array([[0.02960581],
        [0.4334659 ],
        [0.94329902],
        [0.21180146],
        [0.70345637]]), array([[0.02960581],
        [0.4334659 ],
        [0.94329902],
        [0.21180146],
        [0.70345637]]), array([[0.02960581],
        [0.4334659 ],
        [0.94329902],
        [0.21180146],
        [0.70345637]])]

In [17]:
b=[89, 90, 78]

In [18]:
b*3



[89, 90, 78, 89, 90, 78, 89, 90, 78]

In [34]:
np.shape(groundtruth_yx)[0]

NameError: name 'groundtruth_yx' is not defined

In [22]:
x = np.array([[1,2],[3,4]])

In [23]:
np.repeat(x,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [30]:
x=np.random.rand(5,1)

In [31]:
x

array([[0.74240922],
       [0.078088  ],
       [0.41544146],
       [0.59881631],
       [0.70788938]])

In [33]:
np.repeat(x,3, axis=1)

array([[0.74240922, 0.74240922, 0.74240922],
       [0.078088  , 0.078088  , 0.078088  ],
       [0.41544146, 0.41544146, 0.41544146],
       [0.59881631, 0.59881631, 0.59881631],
       [0.70788938, 0.70788938, 0.70788938]])

In [35]:
a=np.random.rand(3,3)

In [36]:
b=np.random.rand(3,3)

In [40]:
a-b


array([[-0.62009745, -0.18109739,  0.36825788],
       [-0.06821778,  0.0143975 ,  0.26694392],
       [-0.09306083,  0.11478142, -0.25944797]])

In [41]:
(a-b).any

<function ndarray.any>